/**
 * convex/schema.ts
 *
 * SkySpecs INVENTORY + SCAN database schema.
 * All tables are defined here with appropriate indexes for efficient queries.
 */

import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

// ─── Shared value types ──────────────────────────────────────────────────────

/**
 * Valid case lifecycle statuses.
 *
 * Full lifecycle:
 *   hangar → assembled → transit_out → deployed → (flagged) → transit_in → received → archived
 *
 * Mirrors CaseStatus in src/types/case-status.ts — both must be kept in sync.
 */
const caseStatus = v.union(
  v.literal("hangar"),       // stored in hangar; not yet assembled
  v.literal("assembled"),    // fully packed, ready to deploy
  v.literal("transit_out"),  // in transit to field site
  v.literal("deployed"),     // actively in use at a field site
  v.literal("flagged"),      // has outstanding issues requiring review
  v.literal("transit_in"),   // in transit returning to base
  v.literal("received"),     // received back at base
  v.literal("archived"),     // decommissioned; no longer in active rotation
);

/** Manifest item inspection states */
const manifestItemStatus = v.union(
  v.literal("unchecked"),
  v.literal("ok"),
  v.literal("damaged"),
  v.literal("missing"),
);

/** Inspection lifecycle */
const inspectionStatus = v.union(
  v.literal("pending"),
  v.literal("in_progress"),
  v.literal("completed"),
  v.literal("flagged"),    // items require review
);

/** Shipment tracking status */
const shipmentStatus = v.union(
  v.literal("label_created"),
  v.literal("picked_up"),
  v.literal("in_transit"),
  v.literal("out_for_delivery"),
  v.literal("delivered"),
  v.literal("exception"),
);

/** Mission status */
const missionStatus = v.union(
  v.literal("planning"),
  v.literal("active"),
  v.literal("completed"),
  v.literal("cancelled"),
);

// ─── Event types for immutable audit trail ───────────────────────────────────

const eventType = v.union(
  v.literal("status_change"),
  v.literal("inspection_started"),
  v.literal("inspection_completed"),
  v.literal("item_checked"),
  v.literal("damage_reported"),
  v.literal("shipped"),
  v.literal("delivered"),
  v.literal("custody_handoff"),
  v.literal("note_added"),
  v.literal("photo_added"),
  v.literal("mission_assigned"),
  v.literal("template_applied"),
);

// ─── Schema ──────────────────────────────────────────────────────────────────

export default defineSchema({
  /**
   * cases — the central entity.
   * A physical equipment case tracked through its full lifecycle.
   */
  cases: defineTable({
    label: v.string(),            // display label e.g. "CASE-001"
    qrCode: v.string(),           // QR payload (scanned by SCAN app)
    qrCodeSource: v.optional(     // how the QR code was assigned
      v.union(
        v.literal("generated"),   // QR generated by the system
        v.literal("external"),    // QR code from an external label / pre-printed asset
      )
    ),
    status: caseStatus,
    templateId: v.optional(v.id("caseTemplates")),
    missionId: v.optional(v.id("missions")),

    // Geographic position of the case (last known)
    lat: v.optional(v.number()),
    lng: v.optional(v.number()),
    locationName: v.optional(v.string()),

    // Custody / assignment
    assigneeId: v.optional(v.string()),    // Kinde user ID
    assigneeName: v.optional(v.string()),

    /**
     * Denormalized shipping tracking fields.
     *
     * Written by the `shipCase` mutation (convex/shipping.ts) when the SCAN
     * app operator ships a case via FedEx.  These fields are intentionally
     * denormalized onto the cases table so that:
     *
     *   1. The M3/M4 in-transit map mode can query `cases` by status="shipping"
     *      with `by_status` index and immediately obtain tracking info without
     *      a secondary join to the `shipments` table.
     *
     *   2. The T3 layout query (`getCaseShippingLayout`) can read the full
     *      shipping summary from a single O(1) `ctx.db.get(caseId)` call.
     *
     *   3. Convex re-evaluates all subscribed queries that read the cases table
     *      (including `listCases`, `getCaseStatus`, and `getCaseShippingLayout`)
     *      within ~100–300 ms of the mutation, satisfying the ≤ 2-second
     *      real-time fidelity requirement between SCAN app action and dashboard
     *      visibility.
     *
     * The canonical full shipment record (with route geometry, tracking events,
     * and `currentLat`/`currentLng`) continues to live in the `shipments` table.
     * These fields are a lightweight summary only.
     *
     * Cleared to `undefined` when the case transitions OUT of "shipping" status
     * (e.g., when marked "returned" after FedEx delivery).
     */
    trackingNumber:  v.optional(v.string()),  // e.g. "794644823741"
    carrier:         v.optional(v.string()),  // always "FedEx" currently
    shippedAt:       v.optional(v.number()),  // epoch ms when shipment created
    destinationName: v.optional(v.string()),  // e.g. "SkySpecs HQ — Ann Arbor"
    destinationLat:  v.optional(v.number()),  // destination coordinates (for M4 pins)
    destinationLng:  v.optional(v.number()),

    /**
     * Denormalized FedEx carrier tracking fields.
     *
     * Written by `updateShipmentStatus` (convex/shipping.ts) when a FedEx
     * tracking refresh returns updated carrier data.  These fields are
     * intentionally denormalized onto the cases table so that:
     *
     *   1. The M3/M4 map modes can show carrier status alongside case status
     *      without a secondary join to the `shipments` table.
     *
     *   2. The T3/T4 layout queries can read the full tracking summary from
     *      a single O(1) `ctx.db.get(caseId)` call.
     *
     *   3. All queries subscribed to the `cases` table (listForMap, getCaseStatus,
     *      getCaseCarrierStatus) automatically re-evaluate within ~100–300 ms
     *      of any tracking refresh, satisfying the ≤ 2-second real-time
     *      fidelity requirement.
     *
     * These fields are cleared to `undefined` when a case transitions to a
     * non-shipping status (e.g., "received" after FedEx delivery).
     *
     * The canonical full tracking data (with complete event timeline) continues
     * to live in the `shipments` table.  These fields are a lightweight summary.
     */

    /**
     * Normalized FedEx carrier tracking status.
     * Mirrors the `shipmentStatus` union from the `shipments` table but stored
     * as a plain string for schema flexibility.
     * Values: "label_created" | "picked_up" | "in_transit" | "out_for_delivery"
     *        | "delivered" | "exception"
     * Updated by `updateShipmentStatus` on each FedEx tracking poll.
     */
    carrierStatus:     v.optional(v.string()),

    /**
     * Estimated delivery date as an ISO 8601 date-time string.
     * Sourced from the FedEx Track API response on each refresh.
     * Example: "2025-06-03T20:00:00Z"
     * Updated by `updateShipmentStatus`; cleared when delivered.
     */
    estimatedDelivery: v.optional(v.string()),

    /**
     * Most recent FedEx scan / tracking event for this case.
     * Sourced from the first element of `events` in the FedEx Track API response.
     * Stored as a structured object for direct rendering in map pin tooltips
     * and T3/T4 layout panels without parsing raw event strings.
     *
     * Updated by `updateShipmentStatus` on each FedEx tracking poll.
     * Undefined when no tracking event has been recorded yet (label_created with
     * no FedEx scan activity).
     */
    lastCarrierEvent:  v.optional(v.object({
      /** ISO 8601 timestamp of the scan event (as returned by FedEx). */
      timestamp:   v.string(),
      /** Short FedEx event type code (e.g., "PU" = Picked Up, "OD" = Out for Delivery). */
      eventType:   v.string(),
      /** Human-readable description of the scan event. */
      description: v.string(),
      /** Location where the scan event occurred. */
      location: v.object({
        city:    v.optional(v.string()),
        state:   v.optional(v.string()),
        country: v.optional(v.string()),
      }),
    })),

    notes: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_mission", ["missionId"])
    .index("by_qr_code", ["qrCode"])
    /**
     * by_label — efficient lookup by human-readable case label (e.g. "CASE-001").
     *
     * Used by `getCaseByQrIdentifier` as a fallback lookup strategy for
     * legacy/physical labels.  When a technician manually enters a case label
     * or scans a legacy barcode that encodes only the human-readable label
     * (not the full QR URL), this index allows an O(log n) point read instead
     * of a full table scan.
     *
     * Labels are stored verbatim (no normalisation in the DB); the query
     * function applies trim() before using this index.
     */
    .index("by_label", ["label"])
    .index("by_updated", ["updatedAt"]),

  /**
   * missions — a field deployment grouping cases together.
   * Maps to M2 (Mission Mode) and M5 (Mission Control) on the dashboard.
   */
  missions: defineTable({
    name: v.string(),
    description: v.optional(v.string()),
    status: missionStatus,

    // Primary location of the mission site
    lat: v.optional(v.number()),
    lng: v.optional(v.number()),
    locationName: v.optional(v.string()),

    // Date range
    startDate: v.optional(v.number()),  // epoch ms
    endDate: v.optional(v.number()),

    // Mission lead
    leadId: v.optional(v.string()),     // Kinde user ID
    leadName: v.optional(v.string()),

    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_updated", ["updatedAt"]),

  /**
   * caseTemplates — predefined packing lists managed via admin UI.
   * Applied to a case to define its expected manifest items.
   */
  caseTemplates: defineTable({
    name: v.string(),
    description: v.optional(v.string()),
    isActive: v.boolean(),
    items: v.array(
      v.object({
        id: v.string(),             // stable item identifier within template
        name: v.string(),
        description: v.optional(v.string()),
        required: v.boolean(),
        category: v.optional(v.string()),
        sortOrder: v.optional(v.number()),
      })
    ),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_active", ["isActive"]),

  /**
   * manifestItems — per-case state for each template item.
   * Created when a template is applied; updated during inspection.
   */
  manifestItems: defineTable({
    caseId: v.id("cases"),
    templateItemId: v.string(),
    name: v.string(),
    status: manifestItemStatus,
    notes: v.optional(v.string()),
    photoStorageIds: v.optional(v.array(v.string())),  // Convex file storage IDs
    checkedAt: v.optional(v.number()),
    checkedById: v.optional(v.string()),   // Kinde user ID
    checkedByName: v.optional(v.string()),
  })
    .index("by_case", ["caseId"])
    .index("by_case_item", ["caseId", "templateItemId"])
    /**
     * by_case_status — compound index for completion-state queries.
     *
     * Enables O(log n) lookups when filtering manifest items by both
     * caseId and status (e.g., "show me all damaged items for CASE-007").
     * Used by:
     *   getChecklistItemsByStatus — real-time items filtered by completion state
     *   getUncheckedItems         — real-time list of items still to inspect
     *
     * Without this index, status-filtered queries would require a full
     * by_case scan + in-memory filter.  Cases with large packing lists
     * (100+ items) benefit from the O(log n + |results|) index path.
     */
    .index("by_case_status", ["caseId", "status"]),

  /**
   * inspections — a single inspection pass on a case.
   * Tracks aggregate progress; individual items are in manifestItems.
   */
  inspections: defineTable({
    caseId: v.id("cases"),
    inspectorId: v.string(),       // Kinde user ID
    inspectorName: v.string(),
    status: inspectionStatus,

    startedAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    notes: v.optional(v.string()),

    // Aggregate counters (denormalized for fast map queries)
    totalItems: v.number(),
    checkedItems: v.number(),
    damagedItems: v.number(),
    missingItems: v.number(),
  })
    .index("by_case", ["caseId"])
    .index("by_status", ["status"])
    /**
     * by_case_status — compound index for per-case active inspection lookups.
     *
     * Enables O(log n + |results|) lookup when filtering inspections by both
     * caseId and status (e.g., "show me all in_progress inspections for CASE-007").
     * Used by:
     *   getActiveInspection       — find the open inspection for a case O(log n + 1)
     *   getChecklistWithInspection — locate in_progress inspection before fallback
     *   mutations/scan.ts          — check if an active inspection already exists
     *                                before auto-creating a new one on deployed transition
     *
     * Without this index, status-filtered lookups on inspections would require
     * a full by_case scan + in-memory filter. Cases with many historical
     * inspection passes (e.g., repeated field deployments) benefit significantly
     * from the O(log n + |active|) index path where |active| is typically 0 or 1.
     */
    .index("by_case_status", ["caseId", "status"]),

  /**
   * shipments — FedEx tracking entries for cases in transit.
   * Maps to M4 (Logistics Mode) on the dashboard.
   */
  shipments: defineTable({
    caseId: v.id("cases"),
    trackingNumber: v.string(),
    carrier: v.string(),          // "FedEx" (only carrier currently)
    status: shipmentStatus,

    // Route geometry
    originLat: v.optional(v.number()),
    originLng: v.optional(v.number()),
    originName: v.optional(v.string()),

    destinationLat: v.optional(v.number()),
    destinationLng: v.optional(v.number()),
    destinationName: v.optional(v.string()),

    // Last known position (from tracking updates)
    currentLat: v.optional(v.number()),
    currentLng: v.optional(v.number()),

    estimatedDelivery: v.optional(v.string()),  // ISO date string

    /**
     * Most recent FedEx scan event for this shipment.
     *
     * Populated by `updateShipmentStatus` when a FedEx tracking poll returns
     * event data.  The `events[0]` element (most recent event) from the
     * FedExTrackingResult is written here so the last known carrier activity
     * is readily accessible without loading the full event history from FedEx.
     *
     * Used by:
     *   - T4 Shipping panel's "Last Event" row
     *   - M4 logistics map pin tooltips
     *   - T5 Audit timeline "Tracking Events" section
     *
     * Undefined when no FedEx scan events have occurred yet (e.g., a shipment
     * that has a label created but has not yet been picked up by FedEx).
     */
    lastEvent: v.optional(v.object({
      /** ISO 8601 timestamp of the scan event (as returned by FedEx). */
      timestamp:   v.string(),
      /** Short FedEx event type code (e.g., "PU" = Picked Up, "OD" = Out for Delivery). */
      eventType:   v.string(),
      /** Human-readable description of the scan event. */
      description: v.string(),
      /** Location where the scan event occurred. */
      location: v.object({
        city:    v.optional(v.string()),
        state:   v.optional(v.string()),
        country: v.optional(v.string()),
      }),
    })),

    shippedAt: v.optional(v.number()),
    deliveredAt: v.optional(v.number()),

    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_case", ["caseId"])
    .index("by_tracking", ["trackingNumber"])
    .index("by_status", ["status"]),

  /**
   * events — immutable append-only audit timeline.
   * Each action on a case is recorded here in order.
   * Supports optional hash chain for FF_AUDIT_HASH_CHAIN.
   */
  events: defineTable({
    caseId: v.id("cases"),
    eventType: eventType,
    userId: v.string(),            // Kinde user ID
    userName: v.string(),
    timestamp: v.number(),         // epoch ms — used for ordering
    data: v.any(),                 // event-specific payload (typed per eventType)

    // Hash chain fields (populated when FF_AUDIT_HASH_CHAIN is enabled)
    hash: v.optional(v.string()),
    prevHash: v.optional(v.string()),
  })
    .index("by_case", ["caseId"])
    .index("by_case_timestamp", ["caseId", "timestamp"]),

  /**
   * custodyRecords — implements the SCAN app `custody_handoffs` entity.
   *
   * This table records every custody handoff between two Kinde users for a
   * specific case.  It is the canonical implementation of the `custody_handoffs`
   * SCAN app entity specified in the data model.  The table name `custodyRecords`
   * is used throughout the codebase; the semantic concept is "custody handoff".
   *
   * Each row captures a single transfer of physical case custody — when a field
   * technician hands a case to a pilot, or a pilot returns it to a logistics
   * coordinator.  Created during the SCAN app custody transfer workflow
   * (convex/custody.ts `handoffCustody` mutation).
   *
   * Relationship to other SCAN entities
   * ─────────────────────────────────────
   *   • scans             — a "handoff" scan event (scanContext = "handoff") creates
   *                         a scans row AND a custodyRecords row in sequence
   *   • events            — handoffCustody also appends a "custody_handoff" event
   *                         to the immutable events table for T5 audit chain
   *   • cases             — cases.assigneeId / assigneeName updated to the new holder
   *
   * Indexes
   * ───────
   *   by_case      — primary per-case lookup; used by getCustodyRecordsByCase
   *                  and getCustodyRecordsByParticipant (dedup union).
   *
   *   by_to_user   — real-time watcher for incoming custodian queries:
   *                  getCustodyRecordsByCustodian(toUserId) and
   *                  useCurrentCustodianCases() on the SCAN app dashboard.
   *                  Allows a field technician to subscribe to all cases they
   *                  have received custody of without a full table scan.
   *
   *   by_from_user — real-time watcher for outgoing custodian queries:
   *                  getCustodyRecordsByTransferrer(fromUserId).
   *                  Used for audit trails showing all handoffs initiated by a
   *                  specific user.
   *
   *   by_case_transferred_at — time-ordered per-case index:
   *                  getLatestCustodyRecord — O(log n + 1) single-row lookup for
   *                  the most recent handoff (.order("desc").first()).
   *                  getCustodyChain — O(log n + |records|) chronological scan
   *                  without in-memory sort (.order("asc")).
   */
  custodyRecords: defineTable({
    caseId: v.id("cases"),
    fromUserId: v.string(),
    fromUserName: v.string(),
    toUserId: v.string(),
    toUserName: v.string(),
    transferredAt: v.number(),
    notes: v.optional(v.string()),
    signatureStorageId: v.optional(v.string()),  // optional signature image
  })
    .index("by_case",      ["caseId"])
    .index("by_to_user",   ["toUserId"])
    .index("by_from_user", ["fromUserId"])
    /**
     * by_case_transferred_at — time-ordered custody chain index.
     *
     * Enables O(log n + 1) lookup of the MOST RECENT custody record for a
     * specific case by combining the caseId equality predicate with
     * descending order on transferredAt.
     *
     * Primary use case:
     *   getLatestCustodyRecord — instead of loading ALL custody records for the
     *   case (by_case index) and picking the maximum transferredAt in memory,
     *   callers can use:
     *     ctx.db.query("custodyRecords")
     *       .withIndex("by_case_transferred_at", q => q.eq("caseId", id))
     *       .order("desc")
     *       .first()
     *   This is O(log n + 1) vs the current O(log n + |records|) + in-memory max.
     *
     * Also used by:
     *   getCustodyChain — chronological ascending scan for T5 audit panel
     *   Time-range custody queries ("all transfers between T1 and T2 for case X")
     *
     * Particularly important for cases that change hands frequently (e.g., a
     * shared sensor kit that rotates between many field technicians over the
     * course of a multi-week deployment).
     */
    .index("by_case_transferred_at", ["caseId", "transferredAt"]),

  /**
   * notifications — in-app notification inbox.
   * No push / email — in-app only per constraints.
   */
  notifications: defineTable({
    userId: v.string(),            // Kinde user ID of recipient
    type: v.string(),              // e.g. "damage_reported", "shipment_delivered"
    title: v.string(),
    message: v.string(),
    caseId: v.optional(v.id("cases")),
    read: v.boolean(),
    createdAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_user_read", ["userId", "read"]),

  /**
   * damage_reports — dedicated table for damage photo submissions.
   *
   * Each row represents a single photo submitted via the SCAN app damage
   * reporting flow.  A damage report is always anchored to a case and
   * optionally linked to a manifest item (when the photo is attached to a
   * specific checklist item) or can be a standalone case-level photo.
   *
   * The T4 dashboard panel subscribes to getDamageReportsByCase which joins
   * this table with manifestItems to produce the unified DamageReport view.
   * The T5 audit panel subscribes to getDamageReportEvents which reads the
   * events table for the immutable audit trail.
   *
   * Convex re-evaluates all subscribed queries that read this table whenever
   * submitDamagePhoto inserts a new row — satisfying the ≤ 2-second real-time
   * fidelity requirement between SCAN app submission and dashboard visibility.
   *
   * Fields
   * ──────
   *   caseId          — parent case (mandatory)
   *   photoStorageId  — Convex file storage ID for the uploaded photo
   *   annotations     — optional array of pin-style annotations placed on the
   *                     photo by the technician in the SCAN app markup tool
   *   severity        — damage severity assessed by the technician
   *   reportedAt      — epoch ms when the photo was submitted
   *   manifestItemId  — optional link to the manifest item being reported
   *   templateItemId  — stable template item ID (for event correlation)
   *   reportedById    — Kinde user ID of the reporting technician
   *   reportedByName  — display name for attribution
   *   notes           — optional free-text notes entered alongside the photo
   */
  damage_reports: defineTable({
    caseId:          v.id("cases"),
    photoStorageId:  v.string(),   // Convex file storage ID
    annotations:     v.optional(
      v.array(
        v.object({
          /** Relative horizontal position (0–1 fraction of photo width). */
          x:     v.number(),
          /** Relative vertical position (0–1 fraction of photo height). */
          y:     v.number(),
          /** Annotation label text shown in the SCAN markup tool. */
          label: v.string(),
          /** Optional hex colour string for the annotation pin. */
          color: v.optional(v.string()),
        })
      )
    ),
    severity:        v.union(
      v.literal("minor"),
      v.literal("moderate"),
      v.literal("severe"),
    ),
    reportedAt:      v.number(),   // epoch ms

    // Optional link to the specific manifest item this photo documents.
    // Null for case-level photos not tied to a specific packing list item.
    manifestItemId:  v.optional(v.id("manifestItems")),
    templateItemId:  v.optional(v.string()),

    // Reporter attribution
    reportedById:    v.string(),   // Kinde user ID
    reportedByName:  v.string(),

    // Optional free-text notes entered with the photo
    notes:           v.optional(v.string()),
  })
    .index("by_case",             ["caseId"])
    .index("by_case_reported_at", ["caseId", "reportedAt"])
    /**
     * by_reported_by — index on the reporting technician's Kinde user ID.
     *
     * Enables O(log n + |results|) lookups when filtering damage reports by
     * reporter (e.g., "show me all damage photos submitted by Alice").
     * Used by:
     *   getDamageReportsByReporter           — all reports for a reporter
     *   getDamageReportsByReporterInRange    — same, scoped to a time window
     *
     * Without this index, by-reporter queries would require a full table scan
     * + in-memory filter, which becomes expensive as fleet damage volume grows.
     */
    .index("by_reported_by",      ["reportedById"])
    /**
     * by_reported_by_at — compound index on (reportedById, reportedAt).
     *
     * Enables O(log n + |range|) seeks for queries like "all damage reports
     * filed by Alice in the last 7 days".  Convex evaluates both the equality
     * predicate (reportedById) and the range bound (reportedAt) in the index
     * before materialising rows.
     *
     * Used by getDamageReportsByReporterInRange.
     */
    .index("by_reported_by_at",   ["reportedById", "reportedAt"])
    /**
     * by_reported_at — fleet-wide time-ordered damage report feed.
     *
     * Used by listDamageReportsByDateRange to scope fleet-wide results to a
     * time window without a full table scan.
     */
    .index("by_reported_at",      ["reportedAt"]),

  /**
   * scans — immutable log of every QR code scan performed by the SCAN mobile app.
   *
   * Each row captures a single scan event: which case was scanned, by whom,
   * when, and where.  The `scans` table is intentionally append-only (no updates
   * or deletes) so it serves as a reliable audit trail of physical case encounters.
   *
   * Relationship to other tables
   * ────────────────────────────
   *   • cases        — the scanned case (by caseId)
   *   • events       — scanCheckIn also appends a status_change event; the scans
   *                    table provides the raw scan history independently of status
   *                    changes (e.g., "same-status" check-ins still create a scan row)
   *   • inspections  — a scan that transitions to "deployed" auto-creates an
   *                    inspection; the inspectionId can be linked via scanContext
   *
   * Why a dedicated scans table?
   * ────────────────────────────
   * The `events` table records business-significant events (status transitions,
   * damage reports, custody handoffs).  The `scans` table records every scan
   * action regardless of whether a status change occurred — enabling queries like:
   *   "When was this case last physically seen and by whom?"
   *   "How many times has Alice scanned cases this week?"
   *   "List all scans in the last 24 hours for cases in transit"
   *
   * The `scanContext` field distinguishes why the scan was initiated:
   *   "check_in"   — scanCheckIn flow (transition status / confirm location)
   *   "inspection" — entering the inspection checklist workflow
   *   "handoff"    — beginning a custody handoff workflow
   *   "lookup"     — informational only (no action taken)
   *
   * Indexes
   * ───────
   *   by_case             — all scans for a specific case, primary per-case lookup
   *   by_case_scanned_at  — time-ordered scan history for a case (T5 timeline)
   *   by_user             — all scans performed by a specific user (SCAN app "My Activity")
   *   by_scanned_at       — fleet-wide recent scan feed (dashboard overview, telemetry)
   *
   * Convex re-evaluates all subscribed queries that read this table whenever a
   * new scan is inserted — satisfying the ≤ 2-second real-time fidelity requirement.
   */
  scans: defineTable({
    /** Convex ID of the case that was scanned. */
    caseId:        v.id("cases"),

    /** Raw QR code payload decoded by the SCAN app camera. */
    qrPayload:     v.string(),

    /** Kinde user ID of the technician who performed the scan. */
    scannedBy:     v.string(),

    /** Display name of the scanning technician (for UI attribution). */
    scannedByName: v.string(),

    /** Epoch ms when the scan occurred (client-side timestamp). */
    scannedAt:     v.number(),

    /**
     * GPS latitude at the time of scan.
     * May be omitted when the device could not obtain a GPS fix.
     */
    lat:           v.optional(v.number()),

    /**
     * GPS longitude at the time of scan.
     * May be omitted when the device could not obtain a GPS fix.
     */
    lng:           v.optional(v.number()),

    /**
     * Human-readable location name at time of scan.
     * E.g. "Site Alpha — Turbine Row 3" or "SkySpecs HQ — Bay 4".
     */
    locationName:  v.optional(v.string()),

    /**
     * Why the scan was initiated.
     * Used to correlate scans with the workflow they triggered.
     *   "check_in"   — status transition / location update
     *   "inspection" — entering the inspection checklist workflow
     *   "handoff"    — beginning a custody handoff workflow
     *   "lookup"     — informational scan with no workflow action
     */
    scanContext:   v.optional(v.string()),

    /**
     * Optional link to the inspection created or continued by this scan.
     * Populated when scanContext = "inspection" or when a check-in
     * transition to "deployed" auto-creates an inspection.
     */
    inspectionId:  v.optional(v.id("inspections")),

    /**
     * Device / browser metadata for diagnostics and telemetry.
     * Free-form JSON string — e.g., user agent, camera type.
     * Not indexed; used for support investigations only.
     */
    deviceInfo:    v.optional(v.string()),
  })
    /**
     * by_case — primary per-case scan lookup.
     * Used by: getScansByCase, getLastScanForCase, SCAN app scan history view.
     */
    .index("by_case",            ["caseId"])
    /**
     * by_case_scanned_at — time-ordered scan history for a single case.
     * Enables O(log n + |results|) range queries when filtering by both
     * caseId and a time window (e.g., "all scans for CASE-007 in the last 7 days").
     * Used by: T5 audit timeline, compliance reports.
     */
    .index("by_case_scanned_at", ["caseId", "scannedAt"])
    /**
     * by_user — all scans performed by a specific technician.
     * Used by: SCAN app "My Activity" tab, getCustodianIdentitySummary diagnostics.
     * Allows a technician to see their full scan history without a full table scan.
     */
    .index("by_user",            ["scannedBy"])
    /**
     * by_scanned_at — fleet-wide time-ordered scan feed.
     * Used by: dashboard overview "Recent Activity", telemetry aggregations,
     * operations monitoring ("no scans in the last N hours" alerts).
     */
    .index("by_scanned_at",      ["scannedAt"]),

  /**
   * checklist_updates — immutable log of each manifest item state change.
   *
   * Each row captures a single update to one checklist item: the item that
   * changed, its previous state, its new state, and who made the change.
   * The `checklist_updates` table is append-only — it accumulates the full
   * history of how a case's packing list was inspected over time.
   *
   * Relationship to other tables
   * ────────────────────────────
   *   • manifestItems    — the CURRENT state of each item lives here;
   *                        checklist_updates records the HISTORY of state changes
   *   • cases            — parent case (via caseId)
   *   • inspections      — the inspection pass under which the update occurred
   *   • damage_reports   — when newStatus = "damaged" and photos are attached,
   *                        a damage_reports row is also created by the SCAN app
   *   • events           — updateChecklistItem also appends item_checked /
   *                        damage_reported to events; checklist_updates provides
   *                        a typed, queryable view of the same history
   *
   * Why a dedicated checklist_updates table?
   * ─────────────────────────────────────────
   * The `manifestItems` table holds the CURRENT state of each item; querying it
   * shows where things stand NOW but not how they got there.  The `events` table
   * holds the history but in a polymorphic `data: any` blob that requires
   * application-level parsing.  The `checklist_updates` table provides:
   *   1. Strongly-typed query access to per-item state history
   *   2. Efficient compound indexes for "all updates to item X" or "all updates
   *      in status 'damaged' for case Y" without parsing event blobs
   *   3. A reactive subscription target — the SCAN app can subscribe to
   *      "updates for this item" and see real-time changes from other users
   *
   * Indexes
   * ───────
   *   by_case              — all checklist updates for a case (T5 audit panel)
   *   by_case_updated_at   — time-ordered update history for a case
   *   by_manifest_item     — all updates for a specific manifest item
   *   by_case_template     — updates for a specific item (by templateItemId) in a case;
   *                          used when the manifestItemId is not yet resolved
   *   by_user              — all updates made by a specific technician
   *   by_case_new_status   — all updates within a case filtered by new status;
   *                          e.g., "all items marked damaged for CASE-007"
   *
   * Convex re-evaluates all subscribed queries that read this table whenever a
   * new update is inserted — providing live checklist progress in both the SCAN
   * app and the INVENTORY dashboard within the ≤ 2-second fidelity window.
   */
  checklist_updates: defineTable({
    /** Convex ID of the parent case. */
    caseId:          v.id("cases"),

    /**
     * Convex ID of the manifest item that was updated.
     * Links this update to the current state row in `manifestItems`.
     */
    manifestItemId:  v.id("manifestItems"),

    /**
     * Stable template item identifier (from caseTemplates.items[].id).
     * Preserved here so the history row can correlate with the template
     * even if the manifestItems row is ever replaced (e.g., template re-applied).
     */
    templateItemId:  v.string(),

    /**
     * Display name of the checklist item at the time of the update.
     * Denormalized so the history row is self-contained and readable without
     * joining to manifestItems or caseTemplates.
     */
    itemName:        v.string(),

    /**
     * Item inspection state BEFORE this update.
     * Enables "undo" UX and diff views in the T5 audit panel.
     */
    previousStatus:  v.union(
      v.literal("unchecked"),
      v.literal("ok"),
      v.literal("damaged"),
      v.literal("missing"),
    ),

    /**
     * Item inspection state AFTER this update.
     * The new state written to manifestItems.status by the same mutation.
     */
    newStatus:       v.union(
      v.literal("unchecked"),
      v.literal("ok"),
      v.literal("damaged"),
      v.literal("missing"),
    ),

    /** Kinde user ID of the technician who made this update. */
    updatedBy:       v.string(),

    /** Display name of the technician (for UI attribution). */
    updatedByName:   v.string(),

    /** Epoch ms when the update was submitted by the SCAN app. */
    updatedAt:       v.number(),

    /**
     * Optional technician notes entered alongside the status change.
     * Copied from the mutation args; same value written to manifestItems.notes.
     */
    notes:           v.optional(v.string()),

    /**
     * Convex file storage IDs for photos attached to this update.
     * Populated when the technician attached damage photos in the SCAN app.
     * Same value written to manifestItems.photoStorageIds.
     */
    photoStorageIds: v.optional(v.array(v.string())),

    /**
     * Structured damage description (only meaningful when newStatus = "damaged").
     * Free-text entered by the technician in the SCAN damage report form.
     */
    damageDescription: v.optional(v.string()),

    /**
     * Damage severity level (only meaningful when newStatus = "damaged").
     * Values: "minor" | "moderate" | "severe"
     */
    damageSeverity:  v.optional(v.string()),

    /**
     * Optional link to the inspection pass under which this update was made.
     * Populated when an active inspection exists for the case at update time.
     * Enables queries like "all updates during inspection X".
     */
    inspectionId:    v.optional(v.id("inspections")),
  })
    /**
     * by_case — all checklist updates for a case.
     * Primary lookup for the T5 audit panel and SCAN app update history.
     * Used by: getChecklistUpdatesByCase, getChecklistUpdateHistory.
     */
    .index("by_case",           ["caseId"])
    /**
     * by_case_updated_at — time-ordered update history for a case.
     * Enables O(log n + |results|) range queries on time windows.
     * Used by: T5 timeline, "show updates in the last N hours", compliance reports.
     */
    .index("by_case_updated_at", ["caseId", "updatedAt"])
    /**
     * by_manifest_item — all updates for a specific manifest item.
     * Enables per-item history subscription: "show me every state change for
     * this battery pack item".  Used by the SCAN app item detail view and the
     * T4 dashboard damage panel's per-item audit trail.
     */
    .index("by_manifest_item",  ["manifestItemId"])
    /**
     * by_case_template — updates for a specific item (by templateItemId) in a case.
     * Compound index enables O(log n + |results|) lookup of all state changes
     * for one template item within one case — useful when the manifestItemId
     * is unknown (e.g., historical queries before manifestItems was populated).
     */
    .index("by_case_template",  ["caseId", "templateItemId"])
    /**
     * by_user — all checklist updates made by a specific technician.
     * Used by: SCAN app "My Activity" tab, technician contribution reports.
     * Allows O(log n + |results|) lookup without a full table scan.
     */
    .index("by_user",           ["updatedBy"])
    /**
     * by_case_new_status — all updates in a case filtered by new status.
     * Enables efficient reactive queries like "subscribe to all items marked
     * damaged for CASE-007 as they come in" — the T4 damage panel uses this.
     * Without this index, the query would require loading all updates for the
     * case and filtering in memory.
     */
    .index("by_case_new_status", ["caseId", "newStatus"]),

  /**
   * users — verified SkySpecs users, created on first Kinde login.
   *
   * Every record is backed by a valid Kinde JWT whose signature has been
   * verified against the Kinde JWKS endpoint.  The `kindeId` field is the
   * stable sub claim from the JWT and is the canonical user identifier used
   * throughout the database (assigneeId, inspectorId, userId in events, etc.).
   *
   * The record is upserted on every successful auth sync so that profile
   * changes in Kinde (name, email, role) are reflected here without requiring
   * a full re-registration.
   *
   * Fields
   * ──────
   *   kindeId    — Kinde `sub` claim (stable, never changes)
   *   email      — user email from the `email` JWT claim
   *   givenName  — first name from the `given_name` JWT claim
   *   familyName — last name from the `family_name` JWT claim
   *   name       — display name (given + family, or email fallback)
   *   picture    — avatar URL from the `picture` JWT claim
   *   orgCode    — Kinde organization code the user belongs to
   *   roles      — Kinde roles assigned to this user
   *   lastLoginAt — epoch ms of the most recent auth sync
   *   createdAt  — epoch ms when the record was first created
   *   updatedAt  — epoch ms when the record was last updated
   */
  users: defineTable({
    kindeId:     v.string(),              // Kinde `sub` claim
    email:       v.string(),
    givenName:   v.optional(v.string()),
    familyName:  v.optional(v.string()),
    name:        v.string(),              // display name
    picture:     v.optional(v.string()), // avatar URL
    orgCode:     v.optional(v.string()), // Kinde org code
    roles:       v.optional(v.array(v.string())),
    lastLoginAt: v.number(),              // epoch ms
    createdAt:   v.number(),
    updatedAt:   v.number(),

    /**
     * themePreference — persisted dark/light mode choice for this user.
     *
     * Written by `setMyThemePreference` (called from the ConvexThemeSync
     * component whenever the user toggles the theme).  Read by
     * `getMyThemePreference` on auth resolution to restore the user's
     * last-saved preference across sessions and devices.
     *
     * Intentionally NOT updated by `upsertUser` so that profile syncs on
     * login never accidentally reset a manually-chosen theme.
     *
     * When undefined (new users, or users who have never explicitly toggled),
     * the client falls back to the OS `prefers-color-scheme` media query.
     */
    themePreference: v.optional(
      v.union(v.literal("light"), v.literal("dark"))
    ),

    /**
     * invDensityPreference — persisted comfy/compact density choice for the
     * INVENTORY dashboard.
     *
     * Written by `setMyDensityPreference` (called from the ConvexDensitySync
     * component whenever the INVENTORY density changes).  Read by
     * `getMyDensityPreferences` on auth resolution to restore the user's
     * last-saved preference across sessions and devices.
     *
     * When undefined, the client falls back to localStorage or the default "comfy".
     */
    invDensityPreference: v.optional(
      v.union(v.literal("comfy"), v.literal("compact"))
    ),

    /**
     * scanDensityPreference — persisted comfy/compact density choice for the
     * SCAN mobile app.
     *
     * Same lifecycle as invDensityPreference but for the /scan/* routes.
     * Independent from invDensityPreference — the two apps have separate
     * density preferences.
     */
    scanDensityPreference: v.optional(
      v.union(v.literal("comfy"), v.literal("compact"))
    ),
  })
    .index("by_kinde_id", ["kindeId"])
    .index("by_email",    ["email"]),

  /**
   * userPreferences — per-user layout preference store.
   *
   * Persists the INVENTORY dashboard and SCAN app layout choices for each
   * authenticated user across sessions and devices.  Unlike the simple scalar
   * preference fields on the `users` table (themePreference, invDensityPreference,
   * scanDensityPreference), this table holds structured layout state that would
   * be awkward to flatten into scalar columns.
   *
   * One row per user.  The row is upserted (created on first save, patched on
   * subsequent saves) by the `setMyLayoutPreferences` mutation, which is called
   * whenever the user changes their active map mode or case layout.  The row is
   * read by `getMyLayoutPreferences` on auth resolution so the client can restore
   * the user's last-saved preferences across browser sessions and devices — a
   * richer guarantee than localStorage alone (which is device-local).
   *
   * Relationship to localStorage
   * ─────────────────────────────
   * The `layout-storage.ts` helpers (readMapMode / writeMapMode / readCaseLayout /
   * writeCaseLayout) provide fast, synchronous, SSR-safe access to the SAME
   * values via localStorage.  This Convex table acts as the cross-device source
   * of truth.  The recommended reconciliation strategy is:
   *   1. On page load: read from localStorage for immediate hydration.
   *   2. When the Convex query resolves: overwrite with the Convex value if it
   *      differs (Convex wins for cross-device sync).
   *   3. On user change: write to both localStorage AND Convex.
   *
   * layoutPreferences fields
   * ─────────────────────────
   *   activeMapMode     — which INVENTORY map view is active ("M1"–"M5").
   *                       M1 = Fleet Overview, M2 = Site Detail,
   *                       M3 = Transit Tracker, M4 = Heat Map,
   *                       M5 = Mission Control (behind FF_MAP_MISSION).
   *
   *   activeCaseLayout  — which case detail panel is active ("T1"–"T5").
   *                       T1 = Summary, T2 = Manifest, T3 = Inspection History,
   *                       T4 = Shipping & Custody, T5 = Audit Hash Chain
   *                       (T5 behind FF_AUDIT_HASH_CHAIN).
   *
   *   layerToggles      — which INVENTORY map overlay layers are currently
   *                       enabled.  Mirrors the LayerEngine's toggle state so
   *                       the user's preferred overlay configuration is restored
   *                       on next visit.  Each key is a SemanticLayerId.
   *
   *   sidebarCollapsed  — whether the INVENTORY side navigation panel is
   *                       collapsed.  Separate from density preference; this is
   *                       purely a layout visibility toggle.
   *
   *   lastViewedCaseId  — Convex ID of the case last open in the detail panel.
   *                       Allows deep-linking restoration: if the user closes and
   *                       reopens the dashboard, the last-viewed case is
   *                       re-selected automatically.
   *
   * Indexes
   * ───────
   *   by_user_id — primary per-user lookup (O(1) point read by Kinde user ID).
   *                The only index needed; one row per user means no range queries.
   */
  userPreferences: defineTable({
    /** Kinde `sub` claim — stable user identifier. Primary lookup key. */
    userId: v.string(),

    /**
     * Structured layout preference bag.
     *
     * All sub-fields are optional so the object can be partially populated
     * (e.g., only `activeMapMode` is stored on a fresh account, other fields
     * arrive as the user interacts with the dashboard).  Callers must apply
     * explicit fallback defaults when a field is absent.
     */
    layoutPreferences: v.object({
      /**
       * Active INVENTORY map mode.
       * "M1" Fleet Overview · "M2" Site Detail · "M3" Transit Tracker ·
       * "M4" Heat Map · "M5" Mission Control (FF_MAP_MISSION)
       */
      activeMapMode: v.optional(
        v.union(
          v.literal("M1"),
          v.literal("M2"),
          v.literal("M3"),
          v.literal("M4"),
          v.literal("M5"),
        )
      ),

      /**
       * Active case detail panel layout.
       * "T1" Summary · "T2" Manifest · "T3" Inspection History ·
       * "T4" Shipping & Custody · "T5" Audit Hash Chain (FF_AUDIT_HASH_CHAIN)
       */
      activeCaseLayout: v.optional(
        v.union(
          v.literal("T1"),
          v.literal("T2"),
          v.literal("T3"),
          v.literal("T4"),
          v.literal("T5"),
        )
      ),

      /**
       * Per-layer toggle state for the INVENTORY map overlay engine.
       * Keys correspond to SemanticLayerIds defined in the LayerEngine.
       * A `true` value means the layer is visible; `false` means hidden.
       * When a key is absent, the layer's default visibility applies.
       */
      layerToggles: v.optional(
        v.object({
          /** Cases currently deployed at field sites. */
          deployed:  v.optional(v.boolean()),
          /** Cases in transit (inbound or outbound). */
          transit:   v.optional(v.boolean()),
          /** Full fleet overview (all case pins). */
          fleet:     v.optional(v.boolean()),
          /** Damage / flagged case indicators. */
          damage:    v.optional(v.boolean()),
          /** Wind turbine / inspection site markers. */
          turbines:  v.optional(v.boolean()),
          /** Status density heat map overlay. */
          heatmap:   v.optional(v.boolean()),
          /** Mission zone polygons (M5 / FF_MAP_MISSION). */
          missions:  v.optional(v.boolean()),
        })
      ),

      /**
       * Whether the INVENTORY side navigation panel is collapsed.
       * Defaults to `false` (expanded) when absent.
       */
      sidebarCollapsed: v.optional(v.boolean()),

      /**
       * Convex document ID (as string) of the case most recently open in the
       * INVENTORY detail panel.  Stored as a plain string (not a typed v.id)
       * so that stale IDs (deleted cases) do not cause schema validation errors.
       * The consumer must call `ctx.db.get` and handle the `null` case.
       */
      lastViewedCaseId: v.optional(v.string()),
    }),

    /** Epoch ms when this row was last written. */
    updatedAt: v.number(),
  })
    /**
     * by_user_id — primary per-user point lookup.
     * Used by: getMyLayoutPreferences (query), setMyLayoutPreferences (mutation).
     * One row per user; no range queries needed.
     */
    .index("by_user_id", ["userId"]),

  /**
   * turbines — wind turbine site markers for the INVENTORY map turbines overlay.
   *
   * Each row represents a single wind turbine (or turbine pad) that is a
   * potential or active deployment target for SkySpecs inspection cases.
   * Records are rendered as map markers on the turbines overlay layer (toggled
   * via the `turbines` SemanticLayerId in the LayerEngine).
   *
   * The `missionId` field links a turbine to a specific deployment mission,
   * enabling the M1 org filter to scope turbine markers alongside case pins.
   *
   * Fields
   * ──────
   *   name          — turbine/pad identifier (e.g. "T-042", "Row 3 North")
   *   lat           — WGS-84 latitude
   *   lng           — WGS-84 longitude
   *   missionId     — optional link to a missions document (for scoping)
   *   siteCode      — optional short site code (e.g. "SITE-A")
   *   status        — operational status of the turbine
   *   hubHeight     — tower hub height in meters (for tooltip metadata)
   *   rotorDiameter — rotor diameter in meters (for tooltip metadata)
   *   notes         — optional free-text notes
   *   createdAt     — epoch ms when the record was created
   *   updatedAt     — epoch ms when the record was last updated
   *
   * Indexes
   * ───────
   *   by_mission — scope turbine markers to a mission for the org filter
   *   by_status  — filter by operational status (active/inactive/decommissioned)
   *   by_updated — ordered iteration for admin UI and export
   */
  turbines: defineTable({
    /** Turbine/pad display identifier, e.g. "T-042" or "Row 3 North". */
    name:          v.string(),
    /** WGS-84 latitude of the turbine base. */
    lat:           v.number(),
    /** WGS-84 longitude of the turbine base. */
    lng:           v.number(),
    /** Optional link to a missions document (scope marker to one deployment). */
    missionId:     v.optional(v.id("missions")),
    /** Optional short site code for grouping turbines by wind farm / sub-site. */
    siteCode:      v.optional(v.string()),
    /** Operational status. */
    status:        v.union(
      v.literal("active"),           // turbine in active inspection rotation
      v.literal("inactive"),         // temporarily out of rotation
      v.literal("decommissioned"),   // permanently retired
    ),
    /** Hub height in meters (informational, shown in tooltip). */
    hubHeight:     v.optional(v.number()),
    /** Rotor diameter in meters (informational, shown in tooltip). */
    rotorDiameter: v.optional(v.number()),
    /** Optional operator notes. */
    notes:         v.optional(v.string()),
    /** Epoch ms when this record was created. */
    createdAt:     v.number(),
    /** Epoch ms when this record was last updated. */
    updatedAt:     v.number(),
  })
    .index("by_mission", ["missionId"])
    .index("by_status",  ["status"])
    .index("by_updated", ["updatedAt"]),

  /**
   * featureFlags — runtime feature flag storage.
   * Supports: FF_AUDIT_HASH_CHAIN, FF_MAP_MISSION, FF_INV_REDESIGN
   */
  featureFlags: defineTable({
    key: v.string(),               // e.g. "FF_MAP_MISSION"
    enabled: v.boolean(),
    description: v.optional(v.string()),
    updatedAt: v.number(),
  })
    .index("by_key", ["key"]),

  /**
   * fedexTokenCache — server-side OAuth token cache.
   *
   * FedEx access tokens are valid for ~3600 seconds (1 hour).  Storing the
   * active token here lets Convex actions share a single token across cold-start
   * invocations rather than re-authenticating on every action call.
   *
   * The `service` field ("fedex") is an extensibility hook in case a second
   * OAuth-protected carrier is added in future — the same table structure works.
   *
   * Row lifecycle:
   *   • Created on first successful FedEx OAuth exchange.
   *   • Patched (in-place update) on each subsequent refresh.
   *   • Read by `getCachedToken` (internal query) inside `getBearerToken`.
   *   • Tokens within EXPIRY_BUFFER_MS (60 s) of expiry are treated as expired
   *     so there is always adequate time to complete an API request.
   *
   * Security:
   *   • This table is only readable via internalQuery / internalMutation —
   *     no public Convex query exposes these tokens to clients.
   *   • Convex database storage is encrypted at rest.
   */
  fedexTokenCache: defineTable({
    /** Service identifier — always "fedex" for now. */
    service:     v.string(),
    /** OAuth 2.0 bearer token issued by FedEx. */
    accessToken: v.string(),
    /** Epoch ms when the token expires (as reported by FedEx, no safety margin). */
    expiresAt:   v.number(),
    /** Epoch ms when this row was first created. */
    createdAt:   v.number(),
    /** Epoch ms when this row was last updated (token refresh). */
    updatedAt:   v.number(),
  })
    .index("by_service", ["service"]),

  /**
   * telemetryEvents — persistent store for client telemetry events.
   *
   * Both the INVENTORY dashboard and SCAN mobile app emit typed telemetry
   * events via the TelemetryClient (src/lib/telemetry.lib.ts).  In production
   * mode, the client batches events and POSTs them to /api/telemetry (Next.js
   * route) which calls the `recordTelemetryBatch` mutation to persist them here.
   *
   * Schema design
   * ─────────────
   * The indexed scalar fields (app, eventCategory, eventName, sessionId,
   * timestamp) are extracted from the full event payload for efficient queries
   * without scanning the full `payload: v.any()` BSON blob.
   *
   * The full event payload (with all category-specific fields) is stored in
   * `payload` for debugging, audit, and analytics export.
   *
   * Indexes
   * ───────
   *   by_app           — filter dashboard analytics by app surface
   *   by_session       — correlate events in a single browser session
   *   by_category      — filter by navigation / user_action / error / performance
   *   by_event_name    — filter/count by specific event name (e.g. PERF_MAP_ENDPOINT)
   *   by_timestamp     — time-range queries for analytics
   *   by_recorded_at   — monitoring / ingestion rate queries
   *
   * Retention
   * ─────────
   * No retention policy is enforced in application code; a scheduled Convex
   * action or database export can be used for long-term archival.
   */
  telemetryEvents: defineTable({
    /** Which app surface fired the event — "inventory" | "scan". */
    app:           v.string(),
    /** High-level category — "navigation" | "user_action" | "error" | "performance". */
    eventCategory: v.string(),
    /** Specific event name, e.g. "perf:map_endpoint" or "scan:action:qr_scanned". */
    eventName:     v.string(),
    /** Ephemeral per-page-load session identifier (UUID v4). */
    sessionId:     v.string(),
    /** Kinde user ID of the authenticated user, if known. */
    userId:        v.optional(v.string()),
    /** Convex case record ID in focus at event time, if applicable. */
    caseId:        v.optional(v.string()),
    /** Epoch ms when the event occurred (client-side clock). */
    timestamp:     v.number(),
    /** Full event payload including all category-specific fields. */
    payload:       v.any(),
    /** Epoch ms when this row was inserted into the database (server clock). */
    recordedAt:    v.number(),
  })
    .index("by_app",        ["app"])
    .index("by_session",    ["sessionId"])
    .index("by_category",   ["eventCategory"])
    .index("by_event_name", ["eventName"])
    .index("by_timestamp",  ["timestamp"])
    .index("by_recorded_at", ["recordedAt"]),
});
